### ISSUE TITLE
[PE-D][Tester B] edit-friend allows name to be replaced by numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W16-4/tp#130]
UG indicates that name must be a string but the app allowed integers to replace name

![image.png](https://raw.githubusercontent.com/imkwokyong/ped/main/files/89c3b858-4538-47b9-aafb-1f1993f0289d.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: imkwokyong/ped#5

**Comment by victorlaiyeeteng** [comment]
Good to take note. Not sure if it's the same issue for plan name.

**Comment by Elijah5399** [comment]
Closing this issue, since add-friend also allows for numerical names to be used. (ie alphanumeric characters and spaces)
